# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: swift:6.3
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        apt update && apt install -y g++-9 autoconf-archive curl zlib1g-dev doxygen wget build-essential
    - name: Install liblo
      run: |
        curl -L -O https://github.com/radarsat1/liblo/releases/download/0.34/liblo-0.34.tar.gz
        tar -xzf liblo-0.34.tar.gz
        rm liblo-0.34.tar.gz
        cd liblo-0.34
        (./configure --enable-static --disable-shared --disable-tests --disable-tools --disable-examples --disable-doc CFLAGS=-fPIC || (cat config.log; false))
        make install
        cd ..
    - name: Install Libmapper
      run: | 
        wget https://github.com/libmapper/libmapper/releases/download/2.5.2/libmapper-2.5.2.tar.gz && tar -xzf libmapper*.tar.gz
        cd libmapper-2.5.2
        ./configure --disable-java --disable-python --disable-csharp --disable-audio 
        make -j4 && make install
        cd ..
    - name: Build
      run: swift build -v
    - name: Build Documentation
      run: |
        swift package --allow-writing-to-directory docs \
          generate-documentation --target Swiftmapper \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path ${{ github.event.repository.name }} \
          --output-path docs
    - name: Upload generated docs as artifact
      id: lib-docs
      uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
      with:
        path: docs
  deploy:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: lib-docs
        uses: actions/deploy-pages@v4
